---
- name: Create VPC Subnet
  local_action:
    module: ec2_vpc_subnet
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    vpc_id: "{{ vpc_id }}"
    cidr: "{{ subnet_cidr }}"
    az:  "{{ aws_region }}{{ subnet_az }}"
    tags:
      Name: "{{ vpc_name }}_subnet"
      cloudforms: true
    state: present
  register: created_subnet

- debug: var=created_vpc
  when: verbose

- name: Set subnet_id
  set_fact:
    subnet_id: "{{ created_subnet.subnet.id }}"
