---
- name: getting datetimestamp
  shell: date +%Y%m%d%H%M%S
  register: datetimestamp

#- debug: msg="datetimestamp {{ datetimestamp.stdout }}"        

- name: dumping database     
  shell: "pg_dump -v -F custom --dbname=postgresql{{":"}}//{{ database_user}}{{":"}}{{ database_password }}@{{ ansible_host }}{{":"}}{{ database_port }}/{{ database_name }} -f {{ database_filename }}"
  register: dumpout

- name: archiving up CloudForms files
  # ansible 2.3 required for archive module
  archive:
    path: "{{ backup_file_list }}"
    dest: "{{ dest_path }}{{ dest_fileprefix }}-{{ datetimestamp.stdout }}.tgz"
    format: gz
  register: archived_files

- debug: msg="backup file => {{ archived_files.dest }}"
