---
- name: vpc_basic
  hosts: localhost
  gather_facts: false

  pre_tasks:
    - name: logging manageiq object
      debug: var=manageiq
      when: manageiq is defined

  roles:
    - role: vpc_network_create

    - role: vpc_subnet_create
      vpc_id: "{{ vpc_id }}"

    - role: vpc_gateway_create
      vpc_id: "{{ vpc_id }}"
      
    - role: vpc_route_create
      vpc_id: "{{ vpc_id }}"
      subnet_id: "{{ subnet_id }}"
      gateway_id: "{{ gateway_id }}"

