---
- name: Launch VMware VM
  local_action:
    module: vmware_guest
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    name: "{{ vm_name }}"
    template: "{{ template }}"
    datacenter: "{{ datacenter }}"
    cluster: "{{ cluster }}"
    folder: "{{ folder }}"
    guest_id: "{{ guest_id }}"
    annotation: "{{ annotation }}"
    notes: "{{ notes }}"
    hardware:
      memory_mb: "{{ memory_mb }}"
      num_cpus: "{{ num_cpus }}"
    wait_for_ip_address: "{{ wait_for_ip_address }}"
    networks: 
      - name: VM Network 2

    state: present
  register: vm

- debug: 
    var: vm
    msg: "{{ item.ipv4 }} {{ vm_name }}"
  with_items: "{{ vm.instance }}"
  when: verbose